// <auto-generated />
using System;
using InsuranceService.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceService.API.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20260313033759_AddUserOtpTable")]
    partial class AddUserOtpTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceService.API.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("claim_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_comment");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("claim_amount");

                    b.Property<DateOnly>("ClaimDate")
                        .HasColumnType("date")
                        .HasColumnName("claim_date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("document_path");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Submitted")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ClaimId")
                        .HasName("PK__Claims__F9CC0896144DC79A");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsuranceService.API.Models.ClaimApprovalHistory", b =>
                {
                    b.Property<int>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("approval_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApprovalId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("ActionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("action_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("approved_amount");

                    b.Property<int>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int")
                        .HasColumnName("claim_id");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("comments");

                    b.Property<string>("DocumentsVerified")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("documents_verified");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("previous_status");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("rejection_reason");

                    b.HasKey("ApprovalId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimApprovalHistories");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId")
                        .HasName("PK__Insuranc__D54EE9B40360DABD");

                    b.ToTable("InsuranceCategories");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceScheme", b =>
                {
                    b.Property<int>("SchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("scheme_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchemeId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxInvestmentAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("max_investment_amount");

                    b.Property<int?>("MaxTerm")
                        .HasColumnType("int")
                        .HasColumnName("max_term");

                    b.Property<decimal?>("MinInvestmentAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("min_investment_amount");

                    b.Property<int?>("MinTerm")
                        .HasColumnType("int")
                        .HasColumnName("min_term");

                    b.Property<DateOnly?>("NewLaunchDate")
                        .HasColumnType("date")
                        .HasColumnName("new_launch_date");

                    b.Property<decimal?>("ProfitRatio")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("profit_ratio");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("scheme_name");

                    b.HasKey("SchemeId")
                        .HasName("PK__Insuranc__8DF8FA63B4C6C668");

                    b.HasIndex("CategoryId");

                    b.ToTable("InsuranceSchemes");
                });

            modelBuilder.Entity("InsuranceService.API.Models.LoanRepaymentSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int?>("DaysOverdue")
                        .HasColumnType("int")
                        .HasColumnName("days_overdue");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int")
                        .HasColumnName("installment_number");

                    b.Property<decimal>("InterestAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("interest_amount");

                    b.Property<bool>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_paid");

                    b.Property<decimal?>("LateFee")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("late_fee");

                    b.Property<int>("LoanId")
                        .HasColumnType("int")
                        .HasColumnName("loan_id");

                    b.Property<decimal>("OutstandingBalance")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("outstanding_balance");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("paid_amount");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime")
                        .HasColumnName("paid_date");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("payment_reference");

                    b.Property<decimal>("PrincipalAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("principal_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("total_amount");

                    b.HasKey("ScheduleId");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanRepaymentSchedules");
                });

            modelBuilder.Entity("InsuranceService.API.Models.NewsAndAnnouncement", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("news_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("PublishedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("published_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("NewsId")
                        .HasName("PK__NewsAndA__4C27CCD8E2DD9B95");

                    b.HasIndex("AuthorId");

                    b.ToTable("NewsAndAnnouncements");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("EmailSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("email_sent");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("email_sent_at");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("message");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("notification_type");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime")
                        .HasColumnName("read_at");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("int")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PaymentReceipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("receipt_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<bool>("EmailSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("email_sent");

                    b.Property<DateTime?>("EmailSentAt")
                        .HasColumnType("datetime")
                        .HasColumnName("email_sent_at");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    b.Property<string>("ReceiptHtml")
                        .HasColumnType("ntext")
                        .HasColumnName("receipt_html");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("receipt_number");

                    b.Property<string>("ReceiptPdfPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("receipt_pdf_path");

                    b.HasKey("ReceiptId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("PaymentReceipts");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("MaturityDate")
                        .HasColumnType("date")
                        .HasColumnName("maturity_date");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("payment_frequency");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("policy_number");

                    b.Property<string>("PolicyStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("policy_status");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("premium_amount");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int")
                        .HasColumnName("scheme_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<decimal>("SumAssured")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("sum_assured");

                    b.Property<int>("TermYears")
                        .HasColumnType("int")
                        .HasColumnName("term_years");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PolicyId")
                        .HasName("PK__Policies__47DA3F0311C450B0");

                    b.HasIndex("SchemeId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PolicyNumber" }, "UQ__Policies__9691687297386018")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyBeneficiary", b =>
                {
                    b.Property<int>("BeneficiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("beneficiary_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficiaryId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("BeneficiaryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("beneficiary_name");

                    b.Property<decimal>("BenefitPercentage")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("benefit_percentage");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("identification_number");

                    b.Property<string>("IdentificationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("identification_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_primary");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("relationship");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("BeneficiaryId");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyBeneficiaries");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsHome", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int?>("BuiltYear")
                        .HasColumnType("int")
                        .HasColumnName("built_year");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("property_address");

                    b.Property<decimal?>("PropertyValue")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("property_value");

                    b.Property<string>("StructureType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("structure_type");

                    b.HasKey("DetailId")
                        .HasName("PK__PolicyDe__38E9A2245B17D7E2");

                    b.HasIndex(new[] { "PolicyId" }, "UQ__PolicyDe__47DA3F0228F3C749")
                        .IsUnique()
                        .HasFilter("[policy_id] IS NOT NULL");

                    b.ToTable("PolicyDetails_Home", (string)null);
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsLife", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("NomineeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nominee_name");

                    b.Property<string>("NomineeRelation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nominee_relation");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.HasKey("DetailId")
                        .HasName("PK__PolicyDe__38E9A22438F371FB");

                    b.HasIndex(new[] { "PolicyId" }, "UQ__PolicyDe__47DA3F02CF575983")
                        .IsUnique()
                        .HasFilter("[policy_id] IS NOT NULL");

                    b.ToTable("PolicyDetails_Life", (string)null);
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMedical", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<decimal?>("AnnualLimit")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("annual_limit");

                    b.Property<string>("CardTier")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("card_tier");

                    b.Property<decimal?>("DentalLimit")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("dental_limit");

                    b.Property<bool?>("HasDirectBilling")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("has_direct_billing");

                    b.Property<string>("HospitalNetworkTier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hospital_network_tier");

                    b.Property<bool?>("IsFamilyFloater")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_family_floater");

                    b.Property<decimal?>("MaternityLimit")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("maternity_limit");

                    b.Property<decimal?>("OutpatientLimit")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("outpatient_limit");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("PreExistingDiseases")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pre_existing_diseases");

                    b.Property<decimal?>("RoomAndBoardLimit")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("room_and_board_limit");

                    b.Property<decimal?>("SurgeryLimit")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("surgery_limit");

                    b.Property<decimal?>("UsedAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(15, 2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("used_amount");

                    b.Property<int?>("WaitingPeriodDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30)
                        .HasColumnName("waiting_period_days");

                    b.HasKey("DetailId")
                        .HasName("PK__PolicyDe__38E9A22431A48E84");

                    b.HasIndex(new[] { "PolicyId" }, "UQ__PolicyDe__47DA3F02095C5CAC")
                        .IsUnique()
                        .HasFilter("[policy_id] IS NOT NULL");

                    b.ToTable("PolicyDetails_Medical", (string)null);
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMotor", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("chassis_number");

                    b.Property<string>("EngineNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("engine_number");

                    b.Property<int?>("ManufacturingYear")
                        .HasColumnType("int")
                        .HasColumnName("manufacturing_year");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vehicle_model");

                    b.Property<string>("VehicleRegNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("vehicle_reg_number");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("DetailId")
                        .HasName("PK__PolicyDe__38E9A22426EED2C7");

                    b.HasIndex(new[] { "PolicyId" }, "UQ__PolicyDe__47DA3F02C801E076")
                        .IsUnique()
                        .HasFilter("[policy_id] IS NOT NULL");

                    b.ToTable("PolicyDetails_Motor", (string)null);
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyLoan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("loan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("date")
                        .HasColumnName("application_date");

                    b.Property<DateOnly?>("ApprovalDate")
                        .HasColumnType("date")
                        .HasColumnName("approval_date");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("interest_rate");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("loan_amount");

                    b.Property<string>("LoanStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Requested")
                        .HasColumnName("loan_status");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LoanId")
                        .HasName("PK__PolicyLo__A1F79554F1962F1B");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("PolicyLoans");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyRenewal", b =>
                {
                    b.Property<int>("RenewalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("renewal_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RenewalId"));

                    b.Property<DateOnly>("NewMaturityDate")
                        .HasColumnType("date")
                        .HasColumnName("new_maturity_date");

                    b.Property<decimal>("NewPremium")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("new_premium");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<DateOnly>("PreviousMaturityDate")
                        .HasColumnType("date")
                        .HasColumnName("previous_maturity_date");

                    b.Property<decimal>("PreviousPremium")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("previous_premium");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("processed_at");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int")
                        .HasColumnName("processed_by");

                    b.Property<DateOnly>("RenewalDate")
                        .HasColumnType("date")
                        .HasColumnName("renewal_date");

                    b.Property<string>("RenewalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("renewal_notes");

                    b.Property<string>("RenewalStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("renewal_status");

                    b.Property<int>("RenewalTermYears")
                        .HasColumnType("int")
                        .HasColumnName("renewal_term_years");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("RenewalId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("PolicyRenewals");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyRider", b =>
                {
                    b.Property<int>("RiderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rider_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiderId"));

                    b.Property<decimal?>("CoverageAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("coverage_amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("RiderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("rider_name");

                    b.Property<decimal>("RiderPremium")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("rider_premium");

                    b.Property<string>("RiderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("rider_type");

                    b.HasKey("RiderId");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyRiders");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicySurrender", b =>
                {
                    b.Property<int>("SurrenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("surrender_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SurrenderId"));

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("admin_notes");

                    b.Property<decimal>("NetPayable")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("net_payable");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("payment_reference");

                    b.Property<int>("PolicyHeldMonths")
                        .HasColumnType("int")
                        .HasColumnName("policy_held_months");

                    b.Property<int>("PolicyHeldYears")
                        .HasColumnType("int")
                        .HasColumnName("policy_held_years");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("processed_at");

                    b.Property<int?>("ProcessedBy")
                        .HasColumnType("int")
                        .HasColumnName("processed_by");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("date")
                        .HasColumnName("request_date");

                    b.Property<DateTime?>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("SurrenderCharges")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("surrender_charges");

                    b.Property<string>("SurrenderReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("surrender_reason");

                    b.Property<string>("SurrenderStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("surrender_status");

                    b.Property<decimal>("SurrenderValue")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("surrender_value");

                    b.Property<decimal>("TotalPremiumPaid")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("total_premium_paid");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("SurrenderId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("PolicySurrenders");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PremiumPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("amount_paid");

                    b.Property<string>("Gateway")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gateway");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("order_code");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transaction_reference");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentId")
                        .HasName("PK__PremiumP__ED1FC9EA4E0C5346");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("PremiumPayments");
                });

            modelBuilder.Entity("InsuranceService.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("InsuranceService.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Customer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370F35449800");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E61644DCC5FA2")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InsuranceService.API.Models.UserOtp", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("OtpId");

                    b.ToTable("UserOtps");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Claim", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany("Claims")
                        .HasForeignKey("PolicyId")
                        .IsRequired()
                        .HasConstraintName("FK__Claims__policy_i__18EBB532");

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Claims__user_id__19DFD96B");

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.ClaimApprovalHistory", b =>
                {
                    b.HasOne("InsuranceService.API.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ClaimApprovalHistory_Users");

                    b.HasOne("InsuranceService.API.Models.Claim", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ClaimApprovalHistory_Claims");

                    b.Navigation("Approver");

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceScheme", b =>
                {
                    b.HasOne("InsuranceService.API.Models.InsuranceCategory", "Category")
                        .WithMany("InsuranceSchemes")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Insurance__categ__693CA210");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InsuranceService.API.Models.LoanRepaymentSchedule", b =>
                {
                    b.HasOne("InsuranceService.API.Models.PolicyLoan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LoanRepaymentSchedule_PolicyLoans");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("InsuranceService.API.Models.NewsAndAnnouncement", b =>
                {
                    b.HasOne("InsuranceService.API.Models.User", "Author")
                        .WithMany("NewsAndAnnouncements")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("FK__NewsAndAn__autho__14270015");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Notification", b =>
                {
                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PaymentReceipt", b =>
                {
                    b.HasOne("InsuranceService.API.Models.PremiumPayment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentReceipts_PremiumPayments");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Policy", b =>
                {
                    b.HasOne("InsuranceService.API.Models.InsuranceScheme", "Scheme")
                        .WithMany("Policies")
                        .HasForeignKey("SchemeId")
                        .IsRequired()
                        .HasConstraintName("FK__Policies__scheme__71D1E811");

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("Policies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Policies__user_i__70DDC3D8");

                    b.Navigation("Scheme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyBeneficiary", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PolicyBeneficiaries_Policies");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsHome", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsHome")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsHome", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PolicyDet__polic__02FC7413");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsLife", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsLife")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsLife", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PolicyDet__polic__75A278F5");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMedical", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsMedical")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsMedical", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PolicyDet__polic__7A672E12");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMotor", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsMotor")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsMotor", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PolicyDet__polic__7F2BE32F");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyLoan", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany("PolicyLoans")
                        .HasForeignKey("PolicyId")
                        .IsRequired()
                        .HasConstraintName("FK__PolicyLoa__polic__0F624AF8");

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("PolicyLoans")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PolicyLoa__user___10566F31");

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyRenewal", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PolicyRenewals_Policies");

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PolicyRenewals_Users");

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyRider", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PolicyRiders_Policies");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicySurrender", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PolicySurrenders_Policies");

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PolicySurrenders_Users");

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PremiumPayment", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany("PremiumPayments")
                        .HasForeignKey("PolicyId")
                        .IsRequired()
                        .HasConstraintName("FK__PremiumPa__polic__09A971A2");

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("PremiumPayments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PremiumPa__user___0A9D95DB");

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.RefreshToken", b =>
                {
                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceCategory", b =>
                {
                    b.Navigation("InsuranceSchemes");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceScheme", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Policy", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("PolicyDetailsHome");

                    b.Navigation("PolicyDetailsLife");

                    b.Navigation("PolicyDetailsMedical");

                    b.Navigation("PolicyDetailsMotor");

                    b.Navigation("PolicyLoans");

                    b.Navigation("PremiumPayments");
                });

            modelBuilder.Entity("InsuranceService.API.Models.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("NewsAndAnnouncements");

                    b.Navigation("Policies");

                    b.Navigation("PolicyLoans");

                    b.Navigation("PremiumPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
