// <auto-generated />
using System;
using InsuranceService.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceService.API.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20260208212509_addCreatedUpdatedAtCategory")]
    partial class addCreatedUpdatedAtCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceService.API.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<string>("AdminComment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateOnly>("ClaimDate")
                        .HasColumnType("date");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClaimId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId");

                    b.ToTable("InsuranceCategories");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceScheme", b =>
                {
                    b.Property<int>("SchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchemeId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxInvestmentAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("MaxTerm")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinInvestmentAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("MinTerm")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NewLaunchDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("ProfitRatio")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SchemeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("InsuranceSchemes");
                });

            modelBuilder.Entity("InsuranceService.API.Models.NewsAndAnnouncement", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NewsId");

                    b.HasIndex("AuthorId");

                    b.ToTable("NewsAndAnnouncements");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("MaturityDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PolicyStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("SumAssured")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("TermYears")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PolicyId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.HasIndex("SchemeId");

                    b.HasIndex("UserId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsHome", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int?>("BuiltYear")
                        .HasColumnType("int");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PropertyValue")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("StructureType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DetailId");

                    b.HasIndex("PolicyId")
                        .IsUnique()
                        .HasFilter("[PolicyId] IS NOT NULL");

                    b.ToTable("PolicyDetailsHomes");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsLife", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("NomineeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomineeRelation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.HasKey("DetailId");

                    b.HasIndex("PolicyId")
                        .IsUnique()
                        .HasFilter("[PolicyId] IS NOT NULL");

                    b.ToTable("PolicyDetailsLives");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMedical", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("HospitalNetworkTier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsFamilyFloater")
                        .HasColumnType("bit");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("PreExistingDiseases")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DetailId");

                    b.HasIndex("PolicyId")
                        .IsUnique()
                        .HasFilter("[PolicyId] IS NOT NULL");

                    b.ToTable("PolicyDetailsMedicals");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMotor", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EngineNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ManufacturingYear")
                        .HasColumnType("int");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleRegNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DetailId");

                    b.HasIndex("PolicyId")
                        .IsUnique()
                        .HasFilter("[PolicyId] IS NOT NULL");

                    b.ToTable("PolicyDetailsMotors");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyLoan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ApprovalDate")
                        .HasColumnType("date");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("LoanStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoanId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("PolicyLoans");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PremiumPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("PremiumPayments");
                });

            modelBuilder.Entity("InsuranceService.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Claim", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany("Claims")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceScheme", b =>
                {
                    b.HasOne("InsuranceService.API.Models.InsuranceCategory", "Category")
                        .WithMany("InsuranceSchemes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InsuranceService.API.Models.NewsAndAnnouncement", b =>
                {
                    b.HasOne("InsuranceService.API.Models.User", "Author")
                        .WithMany("NewsAndAnnouncements")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Policy", b =>
                {
                    b.HasOne("InsuranceService.API.Models.InsuranceScheme", "Scheme")
                        .WithMany("Policies")
                        .HasForeignKey("SchemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("Policies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scheme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsHome", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsHome")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsHome", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsLife", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsLife")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsLife", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMedical", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsMedical")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsMedical", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMotor", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsMotor")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsMotor", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyLoan", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany("PolicyLoans")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("PolicyLoans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PremiumPayment", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany("PremiumPayments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("PremiumPayments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceCategory", b =>
                {
                    b.Navigation("InsuranceSchemes");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceScheme", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Policy", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("PolicyDetailsHome");

                    b.Navigation("PolicyDetailsLife");

                    b.Navigation("PolicyDetailsMedical");

                    b.Navigation("PolicyDetailsMotor");

                    b.Navigation("PolicyLoans");

                    b.Navigation("PremiumPayments");
                });

            modelBuilder.Entity("InsuranceService.API.Models.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("NewsAndAnnouncements");

                    b.Navigation("Policies");

                    b.Navigation("PolicyLoans");

                    b.Navigation("PremiumPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
