// <auto-generated />
using System;
using InsuranceService.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsuranceService.API.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    partial class InsuranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsuranceService.API.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("claim_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<string>("AdminComment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("admin_comment");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("claim_amount");

                    b.Property<DateOnly>("ClaimDate")
                        .HasColumnType("date")
                        .HasColumnName("claim_date");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Submitted")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ClaimId")
                        .HasName("PK__Claims__F9CC0896144DC79A");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("category_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CategoryId")
                        .HasName("PK__Insuranc__D54EE9B40360DABD");

                    b.ToTable("InsuranceCategories");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceScheme", b =>
                {
                    b.Property<int>("SchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("scheme_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchemeId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaxInvestmentAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("max_investment_amount");

                    b.Property<int?>("MaxTerm")
                        .HasColumnType("int")
                        .HasColumnName("max_term");

                    b.Property<decimal?>("MinInvestmentAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("min_investment_amount");

                    b.Property<int?>("MinTerm")
                        .HasColumnType("int")
                        .HasColumnName("min_term");

                    b.Property<DateOnly?>("NewLaunchDate")
                        .HasColumnType("date")
                        .HasColumnName("new_launch_date");

                    b.Property<decimal?>("ProfitRatio")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("profit_ratio");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("scheme_name");

                    b.HasKey("SchemeId")
                        .HasName("PK__Insuranc__8DF8FA63B4C6C668");

                    b.HasIndex("CategoryId");

                    b.ToTable("InsuranceSchemes");
                });

            modelBuilder.Entity("InsuranceService.API.Models.NewsAndAnnouncement", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("news_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("PublishedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("published_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.HasKey("NewsId")
                        .HasName("PK__NewsAndA__4C27CCD8E2DD9B95");

                    b.HasIndex("AuthorId");

                    b.ToTable("NewsAndAnnouncements");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Policy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("MaturityDate")
                        .HasColumnType("date")
                        .HasColumnName("maturity_date");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("payment_frequency");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("policy_number");

                    b.Property<string>("PolicyStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("policy_status");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("premium_amount");

                    b.Property<int>("SchemeId")
                        .HasColumnType("int")
                        .HasColumnName("scheme_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<decimal>("SumAssured")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("sum_assured");

                    b.Property<int>("TermYears")
                        .HasColumnType("int")
                        .HasColumnName("term_years");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PolicyId")
                        .HasName("PK__Policies__47DA3F0311C450B0");

                    b.HasIndex("SchemeId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PolicyNumber" }, "UQ__Policies__9691687297386018")
                        .IsUnique();

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsHome", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int?>("BuiltYear")
                        .HasColumnType("int")
                        .HasColumnName("built_year");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("property_address");

                    b.Property<decimal?>("PropertyValue")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("property_value");

                    b.Property<string>("StructureType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("structure_type");

                    b.HasKey("DetailId")
                        .HasName("PK__PolicyDe__38E9A2245B17D7E2");

                    b.HasIndex(new[] { "PolicyId" }, "UQ__PolicyDe__47DA3F0228F3C749")
                        .IsUnique()
                        .HasFilter("[policy_id] IS NOT NULL");

                    b.ToTable("PolicyDetails_Home", (string)null);
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsLife", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("NomineeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nominee_name");

                    b.Property<string>("NomineeRelation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nominee_relation");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.HasKey("DetailId")
                        .HasName("PK__PolicyDe__38E9A22438F371FB");

                    b.HasIndex(new[] { "PolicyId" }, "UQ__PolicyDe__47DA3F02CF575983")
                        .IsUnique()
                        .HasFilter("[policy_id] IS NOT NULL");

                    b.ToTable("PolicyDetails_Life", (string)null);
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMedical", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("HospitalNetworkTier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hospital_network_tier");

                    b.Property<bool?>("IsFamilyFloater")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_family_floater");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("PreExistingDiseases")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pre_existing_diseases");

                    b.HasKey("DetailId")
                        .HasName("PK__PolicyDe__38E9A22431A48E84");

                    b.HasIndex(new[] { "PolicyId" }, "UQ__PolicyDe__47DA3F02095C5CAC")
                        .IsUnique()
                        .HasFilter("[policy_id] IS NOT NULL");

                    b.ToTable("PolicyDetails_Medical", (string)null);
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMotor", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<string>("ChassisNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("chassis_number");

                    b.Property<string>("EngineNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("engine_number");

                    b.Property<int?>("ManufacturingYear")
                        .HasColumnType("int")
                        .HasColumnName("manufacturing_year");

                    b.Property<int?>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("vehicle_model");

                    b.Property<string>("VehicleRegNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("vehicle_reg_number");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("vehicle_type");

                    b.HasKey("DetailId")
                        .HasName("PK__PolicyDe__38E9A22426EED2C7");

                    b.HasIndex(new[] { "PolicyId" }, "UQ__PolicyDe__47DA3F02C801E076")
                        .IsUnique()
                        .HasFilter("[policy_id] IS NOT NULL");

                    b.ToTable("PolicyDetails_Motor", (string)null);
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyLoan", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("loan_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoanId"));

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("date")
                        .HasColumnName("application_date");

                    b.Property<DateOnly?>("ApprovalDate")
                        .HasColumnType("date")
                        .HasColumnName("approval_date");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("interest_rate");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("loan_amount");

                    b.Property<string>("LoanStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Requested")
                        .HasColumnName("loan_status");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("LoanId")
                        .HasName("PK__PolicyLo__A1F79554F1962F1B");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("PolicyLoans");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PremiumPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(15, 2)")
                        .HasColumnName("amount_paid");

                    b.Property<string>("Gateway")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gateway");

                    b.Property<string>("OrderCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("order_code");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transaction_reference");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("PaymentId")
                        .HasName("PK__PremiumP__ED1FC9EA4E0C5346");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("PremiumPayments");
                });

            modelBuilder.Entity("InsuranceService.API.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("InsuranceService.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Customer")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370F35449800");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E61644DCC5FA2")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Claim", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany("Claims")
                        .HasForeignKey("PolicyId")
                        .IsRequired()
                        .HasConstraintName("FK__Claims__policy_i__18EBB532");

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Claims__user_id__19DFD96B");

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceScheme", b =>
                {
                    b.HasOne("InsuranceService.API.Models.InsuranceCategory", "Category")
                        .WithMany("InsuranceSchemes")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Insurance__categ__693CA210");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InsuranceService.API.Models.NewsAndAnnouncement", b =>
                {
                    b.HasOne("InsuranceService.API.Models.User", "Author")
                        .WithMany("NewsAndAnnouncements")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("FK__NewsAndAn__autho__14270015");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Policy", b =>
                {
                    b.HasOne("InsuranceService.API.Models.InsuranceScheme", "Scheme")
                        .WithMany("Policies")
                        .HasForeignKey("SchemeId")
                        .IsRequired()
                        .HasConstraintName("FK__Policies__scheme__71D1E811");

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("Policies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Policies__user_i__70DDC3D8");

                    b.Navigation("Scheme");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsHome", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsHome")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsHome", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PolicyDet__polic__02FC7413");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsLife", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsLife")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsLife", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PolicyDet__polic__75A278F5");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMedical", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsMedical")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsMedical", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PolicyDet__polic__7A672E12");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyDetailsMotor", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithOne("PolicyDetailsMotor")
                        .HasForeignKey("InsuranceService.API.Models.PolicyDetailsMotor", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__PolicyDet__polic__7F2BE32F");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PolicyLoan", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany("PolicyLoans")
                        .HasForeignKey("PolicyId")
                        .IsRequired()
                        .HasConstraintName("FK__PolicyLoa__polic__0F624AF8");

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("PolicyLoans")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PolicyLoa__user___10566F31");

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.PremiumPayment", b =>
                {
                    b.HasOne("InsuranceService.API.Models.Policy", "Policy")
                        .WithMany("PremiumPayments")
                        .HasForeignKey("PolicyId")
                        .IsRequired()
                        .HasConstraintName("FK__PremiumPa__polic__09A971A2");

                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany("PremiumPayments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__PremiumPa__user___0A9D95DB");

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.RefreshToken", b =>
                {
                    b.HasOne("InsuranceService.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceCategory", b =>
                {
                    b.Navigation("InsuranceSchemes");
                });

            modelBuilder.Entity("InsuranceService.API.Models.InsuranceScheme", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("InsuranceService.API.Models.Policy", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("PolicyDetailsHome");

                    b.Navigation("PolicyDetailsLife");

                    b.Navigation("PolicyDetailsMedical");

                    b.Navigation("PolicyDetailsMotor");

                    b.Navigation("PolicyLoans");

                    b.Navigation("PremiumPayments");
                });

            modelBuilder.Entity("InsuranceService.API.Models.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("NewsAndAnnouncements");

                    b.Navigation("Policies");

                    b.Navigation("PolicyLoans");

                    b.Navigation("PremiumPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
